channels:
- conda-forge
dependencies:
- python=3.9.7
- pip<=21.3.1
- pip:
  - mlflow
  - cloudpickle==2.1.0
  - lz4==3.1.3
  - psutil==5.9.0
  - scikit-learn==1.0.1
  - typing-extensions==3.7.4.3
name: mlflow-env
